use_frameworks!

platform :ios, '9.0'

target 'YDCharts_Example' do
#  pod 'YDCharts', :path => '../'
  pod 'YDCharts', :podspec => '../'
  

  target 'YDCharts_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
